# Generated by Django 5.0.6 on 2024-06-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verify_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verify Date'),
        ),
    ]
